import { HistoryPlugin, PastePipelinePlugin } from '@soeditor/engine';
import {
    AlignmentPlugin,
    BlockquotePlugin,
    BoldPlugin,
    CmsObjectsPlugin,
    CmsPastePlugin,
    DivPlugin,
    FontPlugin,
    HeadingPlugin,
    HorizontalRulePlugin,
    HtmlCleanupPlugin,
    ImagePlugin,
    IndentationPlugin,
    ItalicPlugin,
    LinkPlugin,
    OrderedListPlugin,
    ParagraphPlugin,
    RemoveFormatPlugin,
    SemanticStylesPlugin,
    StrikePlugin,
    SubscriptPlugin,
    SuperscriptPlugin,
    TablePlugin,
    UnderlinePlugin,
    UnorderedListPlugin,
} from '@soeditor/rich-text';
import { ProjectionCoordinatorPlugin } from '@soeditor/projections';
import { UiPlugin } from '@soeditor/ui';

import { createPreset } from './create-preset.js';

/** CMS runtime without host-owned upload or file-manager integrations. */
export const cmsRuntimePreset = createPreset(
    'html',
    [
        HistoryPlugin,
        ProjectionCoordinatorPlugin,
        PastePipelinePlugin,
        CmsPastePlugin,
        DivPlugin,
        HtmlCleanupPlugin,
        ParagraphPlugin,
        HeadingPlugin,
        BoldPlugin,
        ItalicPlugin,
        UnderlinePlugin,
        StrikePlugin,
        SubscriptPlugin,
        SuperscriptPlugin,
        RemoveFormatPlugin,
        FontPlugin,
        AlignmentPlugin,
        IndentationPlugin,
        HorizontalRulePlugin,
        CmsObjectsPlugin,
        SemanticStylesPlugin,
        LinkPlugin,
        OrderedListPlugin,
        UnorderedListPlugin,
        BlockquotePlugin,
        ImagePlugin,
        TablePlugin,
        UiPlugin,
    ],
    [
        'heading',
        '|',
        'bold',
        'italic',
        'underline',
        'strike',
        'subscript',
        'superscript',
        'removeFormat',
        'fontFamily',
        'fontSize',
        'fontColor',
        'fontBackgroundColor',
        'highlight',
        'link',
        'unlink',
        'link-internal',
        '|',
        'orderedList',
        'unorderedList',
        'outdent',
        'indent',
        '|',
        'blockquote',
        'alignLeft',
        'alignCenter',
        'alignRight',
        'horizontalRule',
        'anchor',
        '|',
        'image-actions',
        'table',
    ],
);
