import { HistoryPlugin, PastePipelinePlugin } from '@soeditor/engine';
import { FileManagerPlugin, UploadPlugin } from '@soeditor/file-manager';
import {
    AlignmentPlugin,
    BlockquotePlugin,
    BoldPlugin,
    CmsObjectsPlugin,
    CmsPastePlugin,
    CodeBlockPlugin,
    DivPlugin,
    HtmlCleanupPlugin,
    HeadingPlugin,
    InlineCodePlugin,
    FontPlugin,
    HorizontalRulePlugin,
    ImagePlugin,
    IndentationPlugin,
    ItalicPlugin,
    LinkPlugin,
    OrderedListPlugin,
    ParagraphPlugin,
    RemoveFormatPlugin,
    SemanticStylesPlugin,
    StrikePlugin,
    SubscriptPlugin,
    SuperscriptPlugin,
    CmsTablePlugin,
    UnderlinePlugin,
    UnorderedListPlugin,
} from '@soeditor/rich-text';
import { UiPlugin } from '@soeditor/ui';
import { ProjectionCoordinatorPlugin } from '@soeditor/projections';

import { createPreset } from './create-preset.js';

/** Experimental author-focused HTML preset used by the CMS Classic Editor. */
export const cmsPreset = createPreset(
    'html',
    [
        HistoryPlugin,
        ProjectionCoordinatorPlugin,
        PastePipelinePlugin,
        CmsPastePlugin,
        DivPlugin,
        CodeBlockPlugin,
        HtmlCleanupPlugin,
        ParagraphPlugin,
        HeadingPlugin,
        BoldPlugin,
        ItalicPlugin,
        UnderlinePlugin,
        StrikePlugin,
        SubscriptPlugin,
        SuperscriptPlugin,
        RemoveFormatPlugin,
        FontPlugin,
        InlineCodePlugin,
        AlignmentPlugin,
        IndentationPlugin,
        HorizontalRulePlugin,
        CmsObjectsPlugin,
        SemanticStylesPlugin,
        LinkPlugin,
        OrderedListPlugin,
        UnorderedListPlugin,
        BlockquotePlugin,
        ImagePlugin,
        CmsTablePlugin,
        UiPlugin,
        FileManagerPlugin,
        UploadPlugin,
    ],
    [
        'heading',
        'fontFamily',
        'fontSize',
        'bold',
        'italic',
        'underline',
        'fontColor',
        'fontBackgroundColor',
        'highlight',
        'strike',
        'subscript',
        'superscript',
        'removeFormat',
        '|',
        'alignment',
        'orderedList',
        'unorderedList',
        'outdent',
        'indent',
        'blockquote',
        '|',
        'link',
        'unlink',
        'link-internal',
        'file-link',
        'image-actions',
        'table',
        'horizontalRule',
        'anchor',
    ],
);
