// Keep table-context resources outside the standalone build when that UI is disabled.
const TABLE_CONTEXT_TRANSLATIONS =
    (
        import.meta as ImportMeta & {
            readonly env: Readonly<Record<string, string | undefined>>;
        }
    ).env.SOEDITOR_TABLE_CONTEXT !== 'false';
import { SOURCE_TOOLBAR } from './source-toolbar.js';
import type {
    EditorUiDirection,
    EditorUiTranslationResource,
} from './types.js';
import {
    resolveUiTranslationResources,
    type ResolvedUiTranslation,
} from './translation-resolution.js';

const messages: readonly (readonly [string, string, string])[] = [
    ...(TABLE_CONTEXT_TRANSLATIONS
        ? ([
              ['Baseline', '基线', '基線'],
              ['Border size', '边框大小', '邊框大小'],
              ['Cell HTML', '单元格 HTML', '儲存格 HTML'],
              ['Cell height', '单元格高度', '儲存格高度'],
              ['Cell padding', '单元格内边距', '儲存格內邊距'],
              ['Cell properties', '单元格属性', '儲存格屬性'],
              ['Cell spacing', '单元格间距', '儲存格間距'],
              ['Cell width', '单元格宽度', '儲存格寬度'],
              [
                  'Changes apply to all selected cells.',
                  '更改将应用到所有选中的单元格。',
                  '變更將套用到所有選取的儲存格。',
              ],
              ['Column group', '列组', '欄群組'],
              ['Column span', '列跨度', '欄跨度'],
              ['Edit cell HTML', '编辑单元格 HTML', '編輯儲存格 HTML'],
              [
                  'Edit the HTML inside this cell. Nested tables are not allowed.',
                  '编辑此单元格内的 HTML，不允许嵌套表格。',
                  '編輯此儲存格內的 HTML，不允許巢狀表格。',
              ],
              [
                  'Enter a whole number from 1 to 100.',
                  '请输入 1 到 100 的整数。',
                  '請輸入 1 到 100 的整數。',
              ],
              [
                  'Enter a whole number from 1 to 9999.',
                  '请输入 1 到 9999 的整数。',
                  '請輸入 1 到 9999 的整數。',
              ],
              ['Horizontal alignment', '水平对齐', '水平對齊'],
              ['Footer', '表尾', '表尾'],
              ['Middle', '居中', '置中'],
              ['Percent', '百分比', '百分比'],
              ['Pixels', '像素', '像素'],
              ['Row group', '行组', '列群組'],
              ['Row properties', '行属性', '列屬性'],
              ['Row span', '行跨度', '列跨度'],
              ['Section properties', '分区属性', '區段屬性'],
              ['Table height', '表格高度', '表格高度'],
              ['Table width', '表格宽度', '表格寬度'],
              [
                  'Select complete cells in one rectangular table section.',
                  '请选择同一表格分区内的完整矩形单元格。',
                  '請選擇同一表格分區內的完整矩形儲存格。',
              ],
              ['Merge cells', '合并单元格', '合併儲存格'],
              ['Column width', '列宽', '欄寬'],
              ['Row height', '行高', '列高'],
              ['Limit reached', '已达限制', '已達限制'],
              [
                  'Splitting would exceed table limits.',
                  '拆分将超出表格大小限制。',
                  '分割將超出表格大小限制。',
              ],
              [
                  'Select one cell to split.',
                  '请选择一个单元格进行拆分。',
                  '請選擇一個儲存格進行分割。',
              ],
              [
                  'Select a merged cell to split completely.',
                  '请选择一个已合并的单元格进行完整拆分。',
                  '請選擇一個已合併的儲存格進行完整分割。',
              ],
              [
                  'Cannot merge with the cell in this direction.',
                  '无法与该方向相邻的单元格合并。',
                  '無法與該方向相鄰的儲存格合併。',
              ],
              [
                  'Select one cell to merge with its neighbor.',
                  '请选择一个单元格与相邻单元格合并。',
                  '請選擇一個儲存格與相鄰儲存格合併。',
              ],
              ['Split cell', '拆分单元格', '拆分儲存格'],
              ['Clear cells', '清空单元格', '清空儲存格'],
              ['More table tools', '更多表格工具', '更多表格工具'],
              ['Merge and split cells', '合并与拆分单元格', '合併與分割儲存格'],
              ['Header column', '标题列', '標題欄'],
              ['Header row', '标题行', '標題列'],
              ['Insert row above', '在上方插入行', '插入上方列'],
              ['Insert row below', '在下方插入行', '插入下方列'],
              ['Insert column left', '在左侧插入列', '插入左方欄'],
              ['Insert column right', '在右侧插入列', '插入右方欄'],
              ['Merge cell up', '合并上方单元格', '合併上方儲存格'],
              ['Merge cell right', '合并右侧单元格', '合併右方儲存格'],
              ['Merge cell down', '合并下方单元格', '合併下方儲存格'],
              ['Merge cell left', '合并左侧单元格', '合併左方儲存格'],
              ['Split cell horizontally', '水平拆分单元格', '水平分割儲存格'],
              ['Split cell vertically', '垂直拆分单元格', '垂直分割儲存格'],
              ['Merge selected cells', '合并所选单元格', '合併所選儲存格'],
              ['Delete row', '删除行', '刪除列'],
              ['Delete column', '删除列', '刪除欄'],
              ['Delete table', '删除表格', '刪除表格'],
              ['Select column', '选择列', '選取欄'],
              ['Select row', '选择行', '選取列'],
              ['Toggle header cell', '切换表头单元格', '切換表頭儲存格'],
          ] satisfies readonly (readonly [string, string, string])[])
        : []),
    ['Image tools', '图片工具', '圖片工具'],
    ['Uploading', '正在上传', '正在上傳'],
    ['Upload failed', '上传失败', '上傳失敗'],
    ['Upload complete', '上传完成', '上傳完成'],
    ['Upload cancelled', '已取消上传', '已取消上傳'],
    ['Retry', '重试', '重試'],
    ['Close', '关闭', '關閉'],
    ['Mixed', '混合', '混合'],
    ['More text styles', '更多文字格式', '更多文字格式'],
    ['Mixed formatting', '混合格式', '混合格式'],
    ['Formatting unavailable', '格式不可用', '格式無法使用'],
    ['Ordered list styles', '编号列表样式', '編號清單樣式'],
    ['Unordered list styles', '符号列表样式', '項目符號清單樣式'],
    ['Decimal', '数字编号', '數字編號'],
    ['Decimal with leading zero', '带前导零的数字', '含前導零的數字'],
    ['Lowercase Roman', '小写罗马数字', '小寫羅馬數字'],
    ['Uppercase Roman', '大写罗马数字', '大寫羅馬數字'],
    ['Lowercase letters', '小写字母', '小寫字母'],
    ['Uppercase letters', '大写字母', '大寫字母'],
    ['Filled circle', '实心圆', '實心圓'],
    ['Hollow circle', '空心圆', '空心圓'],
    ['Square', '方块', '方塊'],
    ['Add attribute', '添加属性', '新增屬性'],
    ['Additional attributes', '附加属性', '附加屬性'],
    ['Added attributes', '已添加属性', '已新增屬性'],
    [
        'Add standard or CMS attributes. Reserved names are blocked.',
        '可添加标准或 CMS 属性；保留属性名会被阻止。',
        '可新增標準或 CMS 屬性；保留屬性名稱會被阻擋。',
    ],
    ['Attribute name', '属性名', '屬性名稱'],
    ['Attribute value', '属性值', '屬性值'],
    [
        'Choose or enter an attribute name',
        '选择或输入属性名',
        '選擇或輸入屬性名稱',
    ],
    ['No additional attributes.', '暂无附加属性。', '尚無附加屬性。'],
    ['Remove attribute', '移除属性', '移除屬性'],
    ['Invalid attribute.', '属性无效。', '屬性無效。'],
    ['Accessibility help', '无障碍帮助', '無障礙說明'],
    ['Accessible label', '无障碍标签', '無障礙標籤'],
    ['Align center', '居中对齐', '置中對齊'],
    ['Align left', '左对齐', '靠左對齊'],
    ['Align right', '右对齐', '靠右對齊'],
    ['Add', '添加', '新增'],
    ['Add relationship', '添加链接关系', '新增連結關係'],
    ['Advanced settings', '高级设置', '進階設定'],
    ['Alignment', '对齐方式', '對齊方式'],
    ['Automatic', '自动', '自動'],
    ['Body', '表体', '表體'],
    ['Bottom', '底部', '底部'],
    ['Center', '居中', '置中'],
    ['Cell', '单元格', '儲存格'],
    ['Cell classes', '单元格类名', '儲存格類別'],
    ['Cell height unit', '单元格高度单位', '儲存格高度單位'],
    ['Cell width unit', '单元格宽度单位', '儲存格寬度單位'],
    ['Custom', '自定义', '自訂'],
    ['Custom width', '自定义宽度', '自訂寬度'],
    ['Default', '默认', '預設'],
    ['Header', '表头', '表頭'],
    ['Left', '左对齐', '靠左'],
    ['Right', '右对齐', '靠右'],
    ['Section', '分区', '區段'],
    ['Summary', '摘要', '摘要'],
    ['Table height unit', '表格高度单位', '表格高度單位'],
    ['Table width unit', '表格宽度单位', '表格寬度單位'],
    ['Top', '顶部', '頂端'],
    ['Width unit', '宽度单位', '寬度單位'],
    ['Alternative text', '替代文本', '替代文字'],
    ['Anchor name', '锚点名称', '錨點名稱'],
    ['Background color', '背景色', '背景色'],
    ['Block quote', '块引用', '區塊引言'],
    ['Bold', '粗体', '粗體'],
    [
        'Bold: Control or Command plus B',
        '粗体：Control 或 Command 加 B',
        '粗體：Control 或 Command 加 B',
    ],
    ['Cancel', '取消', '取消'],
    ['Changes saved', '更改已保存', '變更已儲存'],
    ['Caption', '标题', '標題'],
    ['Character', '字符', '字元'],
    ['Choose a common target', '选择常用目标', '選擇常用目標'],
    ['Choose block style', '选择段落样式', '選擇段落樣式'],
    ['Choose color', '选择颜色', '選擇顏色'],
    ['Choose file link', '选择文件链接', '選擇檔案連結'],
    ['Choose internal link', '选择内部链接', '選擇內部連結'],
    ['Close preview', '关闭预览', '關閉預覽'],
    [
        'Close a dialog or menu: Escape',
        '关闭对话框或菜单：Escape',
        '關閉對話框或選單：Escape',
    ],
    ['CMS placeholder', 'CMS 占位符', 'CMS 佔位符'],
    ['Collapse editor toolbar', '折叠编辑器工具栏', '收合編輯器工具列'],
    [
        'Context menu: Shift plus F10',
        '上下文菜单：Shift 加 F10',
        '內容功能表：Shift 加 F10',
    ],
    ['Columns', '列数', '欄數'],
    ['Common relationships', '常用链接关系', '常用連結關係'],
    ['Common target', '常用目标', '常用目標'],
    ['Color value', '颜色值', '顏色值'],
    ['Custom color', '自定义颜色', '自訂顏色'],
    ['Custom relationship', '自定义链接关系', '自訂連結關係'],
    ['Custom target name', '自定义目标名称', '自訂目標名稱'],
    ['Apply color', '应用颜色', '套用顏色'],
    ['document', '文档', '文件'],
    ['Displayed text', '显示文本', '顯示文字'],
    ['Edit', '编辑', '編輯'],
    ['Edit link', '编辑链接', '編輯連結'],
    ['Editing view', '编辑视图', '編輯檢視'],
    ['Embed', '嵌入内容', '嵌入內容'],
    [
        'Enter 1–9999 px (px is optional) or 1%–100%.',
        '请输入 1–9999 px（px 可省略）或 1%–100%。',
        '請輸入 1–9999 px（px 可省略）或 1%–100%。',
    ],
    ['Editor context menu', '编辑器上下文菜单', '編輯器內容功能表'],
    ['Editor notifications', '编辑器通知', '編輯器通知'],
    ['Editor toolbar', '编辑器工具栏', '編輯器工具列'],
    ['Expand editor toolbar', '展开编辑器工具栏', '展開編輯器工具列'],
    ['Format HTML', '格式化 HTML', '格式化 HTML'],
    ['Clear selected cells', '清空所选单元格', '清空所選儲存格'],
    ['Font size', '字号', '字體大小'],
    [
        'For example: 640, 640px, or 70%',
        '例如：640、640px 或 70%',
        '例如：640、640px 或 70%',
    ],
    ['Header scope', '表头范围', '表頭範圍'],
    ['Heading', '标题', '標題'],
    ['Apply', '应用', '套用'],
    ['Help', '帮助', '說明'],
    ['Height', '高度', '高度'],
    ['Horizontal rule', '水平线', '水平線'],
    ['Image', '图片', '圖片'],
    ['Image and description', '图片与说明', '圖片與說明'],
    ['Image properties', '图片属性', '圖片屬性'],
    ['Image title', '图片标题', '圖片標題'],
    ['Image URL', '图片地址', '圖片網址'],
    ['Indent', '增加缩进', '增加縮排'],
    ['Insert link', '插入链接', '插入連結'],
    ['Column', '列', '欄'],
    ['Row', '行', '列'],
    ['Insert column after', '在后面插入列', '在後方插入欄'],
    ['Insert column before', '在前面插入列', '在前方插入欄'],
    ['Insert row after', '在后面插入行', '在後方插入列'],
    ['Insert row before', '在前面插入行', '在前方插入列'],
    ['Italic', '斜体', '斜體'],
    [
        'Italic: Control or Command plus I',
        '斜体：Control 或 Command 加 I',
        '斜體：Control 或 Command 加 I',
    ],
    [
        'Line break without a new paragraph: Shift plus Enter',
        '段内换行（不新建段落）：Shift 加 Enter',
        '段內換行（不新增段落）：Shift 加 Enter',
    ],
    [
        'Invalid color. Use #2563eb, rgb(37, 99, 235), hsl(217, 91%, 60%), or a color name.',
        '颜色格式不正确。请输入 #2563eb、rgb(37, 99, 235)、hsl(217, 91%, 60%) 或颜色名称。',
        '顏色格式不正確。請輸入 #2563eb、rgb(37, 99, 235)、hsl(217, 91%, 60%) 或顏色名稱。',
    ],
    ['Justify', '两端对齐', '左右對齊'],
    ['Link', '链接', '連結'],
    ['Link URL', '链接地址', '連結網址'],
    ['Link target', '链接打开位置', '連結開啟位置'],
    ['Lock aspect ratio', '锁定宽高比', '鎖定寬高比'],
    ['Resize image', '调整图片尺寸', '調整圖片尺寸'],
    [
        'Block tools failed to load. Please try again.',
        '区块工具加载失败，请重试。',
        '區塊工具載入失敗，請重試。',
    ],
    [
        'Insert paragraph before this block',
        '在此区块前插入段落',
        '在此區塊前插入段落',
    ],
    [
        'Insert paragraph after this block',
        '在此区块后插入段落',
        '在此區塊後插入段落',
    ],
    ['Maximize', '最大化', '最大化'],
    ['Maximize editor', '最大化编辑器', '最大化編輯器'],
    ['Named anchor', '命名锚点', '命名錨點'],
    ['New paragraph: Enter', '新建段落：Enter', '新增段落：Enter'],
    [
        'New window or tab (_blank)',
        '新窗口或标签页（_blank）',
        '新視窗或分頁（_blank）',
    ],
    ['Same window', '当前窗口', '目前視窗'],
    ['Ordered list', '有序列表', '有序清單'],
    ['Optional tooltip', '可选提示文字', '選填提示文字'],
    ['Outdent', '减少缩进', '減少縮排'],
    ['Page break', '分页符', '分頁符號'],
    ['Paragraph', '段落', '段落'],
    ['Preset colors', '预设颜色', '預設顏色'],
    ['Remove image', '移除图片', '移除圖片'],
    ['Responsive CSS classes', '响应式 CSS 类', '響應式 CSS 類別'],
    ['Responsive image settings', '响应式图片设置', '響應式圖片設定'],
    ['Responsive sizes', '响应式尺寸规则', '響應式尺寸規則'],
    ['Responsive sources', '响应式图片源', '響應式圖片來源'],
    ['Size and placement', '尺寸与位置', '尺寸與位置'],
    ['Placeholder name', '占位符名称', '佔位符名稱'],
    ['Redo', '重做', '重做'],
    ['Recent colors', '最近使用的颜色', '最近使用的顏色'],
    ['Same window (_self)', '当前窗口（_self）', '目前視窗（_self）'],
    ['Relationship', '链接关系', '連結關係'],
    ['Remove format', '清除格式', '清除格式'],
    ['Remove link', '移除链接', '移除連結'],
    ['Remove media', '移除媒体', '移除媒體'],
    ['Delete selected columns', '删除所选列', '刪除所選欄'],
    ['Delete selected rows', '删除所选行', '刪除所選列'],
    ['Resize editor height', '调整编辑器高度', '調整編輯器高度'],
    ['Responsive classes', '响应式类名', '響應式類別'],
    ['Restore', '还原', '還原'],
    ['Restore editor size', '还原编辑器大小', '還原編輯器大小'],
    ['Rich text editor', '富文本编辑器', 'RTF 編輯器'],
    ['Row classes', '行类名', '列類別'],
    ['Rows', '行数', '列數'],
    ['Saved', '已保存', '已儲存'],
    ['Save', '保存', '儲存'],
    ['Save conflict', '保存冲突', '儲存衝突'],
    ['Save failed', '保存失败', '儲存失敗'],
    ['Saving', '正在保存', '正在儲存'],
    [
        'Show or hide editor toolbar',
        '显示或隐藏编辑器工具栏',
        '顯示或隱藏編輯器工具列',
    ],
    ['Select table', '选择表格', '選取表格'],
    ['Source', '源码', '原始碼'],
    ['Special character', '特殊字符', '特殊字元'],
    ['Strike', '删除线', '刪除線'],
    ['Strikethrough', '删除线', '刪除線'],
    ['Subscript', '下标', '下標'],
    ['Superscript', '上标', '上標'],
    ['Table', '表格', '表格'],
    ['Table cell properties', '单元格属性', '儲存格屬性'],
    ['Table properties', '表格属性', '表格屬性'],
    ['Table row properties', '表格行属性', '表格列屬性'],
    ['Target', '目标', '目標'],
    ['Parent frame (_parent)', '父级框架（_parent）', '父層框架（_parent）'],
    ['Top frame (_top)', '顶级框架（_top）', '頂層框架（_top）'],
    ['Text color', '文字颜色', '文字顏色'],
    ['Text shown to readers', '向读者显示的文字', '向讀者顯示的文字'],
    ['Title', '标题', '標題'],
    ['Toolbar', '工具栏', '工具列'],
    ['Underline', '下划线', '底線'],
    ['Undo', '撤销', '復原'],
    [
        'Undo: Control or Command plus Z',
        '撤销：Control 或 Command 加 Z',
        '復原：Control 或 Command 加 Z',
    ],
    [
        'Redo: Control or Command plus Shift plus Z',
        '重做：Control 或 Command 加 Shift 加 Z',
        '重做：Control 或 Command 加 Shift 加 Z',
    ],
    [
        'Select multiple table cells: Shift plus click another cell',
        '多选表格单元格：按住 Shift 再单击另一个单元格',
        '多選表格儲存格：按住 Shift 再按一下另一個儲存格',
    ],
    ['Unordered list', '无序列表', '無序清單'],
    ['Unsaved', '未保存', '未儲存'],
    ['Retry save', '重试保存', '重試儲存'],
    ['URL', '地址', '網址'],
    ['Update link', '更新链接', '更新連結'],
    ['Update image', '更新图片', '更新圖片'],
    ['Vertical alignment', '垂直对齐', '垂直對齊'],
    ['Visible caption', '可见说明文字', '可見說明文字'],
    ['Visual', '可视化', '視覺化'],
    ['Width', '宽度', '寬度'],
    [
        'Width must be 1–9999 px or 1%–100%.',
        '宽度必须是 1–9999 px 或 1%–100%。',
        '寬度必須是 1–9999 px 或 1%–100%。',
    ],
    ['Width (px or %)', '宽度（px 或 %）', '寬度（px 或 %）'],
    ['characters', '字符', '字元'],
    ['source characters', '源码字符', '原始碼字元'],
    ['words', '词', '詞'],
    [
        'Use Tab to enter controls and Arrow keys to move within toolbars and menus.',
        '使用 Tab 进入控件，并使用方向键在工具栏和菜单中移动。',
        '使用 Tab 進入控制項，並使用方向鍵在工具列和選單中移動。',
    ],
    [
        'Describe the image for people who cannot see it.',
        '为无法看到图片的用户描述图片内容。',
        '為無法看到圖片的使用者描述圖片內容。',
    ],
    ...(SOURCE_TOOLBAR
        ? ([
              ['WYSIWYG + Preview', '所见即所得 + 预览', '所見即所得 + 預覽'],
              ['Source + Preview', '源码 + 预览', '原始碼 + 預覽'],
              ['WYSIWYG + Source', '所见即所得 + 源码', '所見即所得 + 原始碼'],
              [
                  'WYSIWYG + Source + Preview',
                  '所见即所得 + 源码 + 预览',
                  '所見即所得 + 原始碼 + 預覽',
              ],
              ['Format source HTML', '格式化 HTML 源码', '格式化 HTML 原始碼'],
              ['Minify source HTML', '压缩 HTML 源码', '壓縮 HTML 原始碼'],
              [
                  'Switch to HTML source editing',
                  '切换到 HTML 源码编辑',
                  '切換到 HTML 原始碼編輯',
              ],
              [
                  'Switch to Source editing',
                  '切换到 Source 编辑',
                  '切換到 Source 編輯',
              ],
              [
                  'Switch to visual editing',
                  '切换到可视化编辑',
                  '切換到視覺化編輯',
              ],
              [
                  'Switch to WYSIWYG editing',
                  '切换到 WYSIWYG 编辑',
                  '切換到 WYSIWYG 編輯',
              ],
          ] satisfies readonly (readonly [string, string, string])[])
        : []),
];
const simplifiedChinese: Readonly<Record<string, string>> = Object.freeze(
    Object.fromEntries(messages.map(([key, cn]) => [key, cn])),
);
const traditionalChinese: Readonly<Record<string, string>> = Object.freeze(
    Object.fromEntries(messages.map(([key, , tw]) => [key, tw])),
);

/** Built-in complete baseline resources for the qualified classic chrome. */
export const builtInUiTranslations: readonly EditorUiTranslationResource[] =
    Object.freeze([
        Object.freeze({ direction: 'ltr', locale: 'en', messages: {} }),
        Object.freeze({
            direction: 'ltr',
            locale: 'zh-CN',
            messages: simplifiedChinese,
        }),
        Object.freeze({
            direction: 'ltr',
            locale: 'zh-TW',
            messages: traditionalChinese,
        }),
    ]);

export type { ResolvedUiTranslation } from './translation-resolution.js';

export function resolveUiTranslation(
    requestedLocale = 'en',
    resources: readonly EditorUiTranslationResource[] = [],
    requestedDirection?: EditorUiDirection,
): ResolvedUiTranslation {
    return resolveUiTranslationResources(
        requestedLocale,
        [...builtInUiTranslations, ...resources],
        requestedDirection,
    );
}
